# Generated by Django 5.0.7 on 2024-12-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListShop',
        ),
    ]
