# Generated by Django 5.0.7 on 2024-12-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
